import React from "react";
import CocktailList from ".";
import { render, screen } from "../../../../../../utils/test-utils";

describe("CocktailList component", function () {
    it("Test CocktailList component snapshot", () => {
        const testCocktailArray = [
            {
                "idDrink": "13940",
                "strDrink": "69 Special",
                "strDrinkAlternate": null,
                "strTags": null,
                "strVideo": null,
                "strCategory": "Ordinary Drink",
                "strIBA": null,
                "strAlcoholic": "Alcoholic",
                "strGlass": "Collins Glass",
                "strInstructions": "Pour 2 oz. gin. Add 4 oz. 7-up. Add Lemon Juice for flavor. If you are weak, top up glass with more 7-Up.",
                "strInstructionsES": null,
                "strInstructionsDE": "Gießen Sie 6 cl. Gin. Füge 12 cl. 7-up hinzu. Füge Zitronensaft für den Geschmack hinzu. Wenn Sie zu schwach sind, füllen Sie das Glas mit mehr 7-Up auf.",
                "strInstructionsFR": null,
                "strInstructionsIT": "Versare 60ml di Gin.\r\nAggiungi 120ml di  7 Up/Sprite.\r\nAggiungi il succo di limone per insaporire.\r\nSe sei debole, rabbocca il bicchiere con più 7-Up/Sprite.",
                "strInstructionsZH-HANS": null,
                "strInstructionsZH-HANT": null,
                "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/vqyxqx1472669095.jpg",
                "strIngredient1": "Gin",
                "strIngredient2": "7-Up",
                "strIngredient3": "Lemon juice",
                "strIngredient4": null,
                "strIngredient5": null,
                "strIngredient6": null,
                "strIngredient7": null,
                "strIngredient8": null,
                "strIngredient9": null,
                "strIngredient10": null,
                "strIngredient11": null,
                "strIngredient12": null,
                "strIngredient13": null,
                "strIngredient14": null,
                "strIngredient15": null,
                "strMeasure1": "2 oz dry ",
                "strMeasure2": "4 oz ",
                "strMeasure3": "0.75 oz ",
                "strMeasure4": null,
                "strMeasure5": null,
                "strMeasure6": null,
                "strMeasure7": null,
                "strMeasure8": null,
                "strMeasure9": null,
                "strMeasure10": null,
                "strMeasure11": null,
                "strMeasure12": null,
                "strMeasure13": null,
                "strMeasure14": null,
                "strMeasure15": null,
                "strImageSource": null,
                "strImageAttribution": null,
                "strCreativeCommonsConfirmed": "No",
                "dateModified": "2016-08-31 19:44:55"
            },
            {
                "idDrink": "12864",
                "strDrink": "Apple Cider Punch",
                "strDrinkAlternate": null,
                "strTags": null,
                "strVideo": null,
                "strCategory": "Punch / Party Drink",
                "strIBA": null,
                "strAlcoholic": "Optional alcohol",
                "strGlass": "Collins Glass",
                "strInstructions": "If you use the whole all spice and cloves, tie them in cheesecloth. Heat the mixture. Stir occasionally. If you want an alcoholic drink, rum would be nice.",
                "strInstructionsES": "Si va a usar todo el condimento y los clavos, átelos en una gasa. Calentar la mezcla. Revuelva ocasionalmente. Si quieres una bebida alcohólica, el ron sería agradable.",
                "strInstructionsDE": "Wenn du das ganze Gewürz und die Nelken verwendest, bindest du sie in ein Seihtuch. Die Mischung erhitzen. Gelegentlich umrühren. Wenn du ein alkoholisches Getränk willst, wäre Rum schön.",
                "strInstructionsFR": null,
                "strInstructionsIT": "Versa tutto in un pentolino tranne spezie e chiodi di garofano, legali in una garza e tienili in ammollo.\r\nRiscalda la miscela. Mescola di tanto in tanto. Se vuoi una bevanda alcolica puoi aggiungere un po’ di Rum.",
                "strInstructionsZH-HANS": null,
                "strInstructionsZH-HANT": null,
                "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/xrqxuv1454513218.jpg",
                "strIngredient1": "Apple cider",
                "strIngredient2": "Brown sugar",
                "strIngredient3": "Lemonade",
                "strIngredient4": "Orange juice",
                "strIngredient5": "Cloves",
                "strIngredient6": "Allspice",
                "strIngredient7": "Nutmeg",
                "strIngredient8": "Cinnamon",
                "strIngredient9": null,
                "strIngredient10": null,
                "strIngredient11": null,
                "strIngredient12": null,
                "strIngredient13": null,
                "strIngredient14": null,
                "strIngredient15": null,
                "strMeasure1": "4 qt ",
                "strMeasure2": "1 cup ",
                "strMeasure3": "6 oz frozen ",
                "strMeasure4": "6 oz frozen ",
                "strMeasure5": "6 whole ",
                "strMeasure6": "6 whole ",
                "strMeasure7": "1 tsp ground ",
                "strMeasure8": "3 sticks ",
                "strMeasure9": null,
                "strMeasure10": null,
                "strMeasure11": null,
                "strMeasure12": null,
                "strMeasure13": null,
                "strMeasure14": null,
                "strMeasure15": null,
                "strImageSource": null,
                "strImageAttribution": null,
                "strCreativeCommonsConfirmed": "No",
                "dateModified": "2016-02-03 15:26:58"
            }
        ]
        render(<CocktailList cocktailData={testCocktailArray} isLoading={false} />)
        expect(screen).toMatchSnapshot();
    })
});